"""empty message

Revision ID: 12a1c8563185
Revises: 021c397b1fb3
Create Date: 2022-06-07 17:29:01.949857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a1c8563185'
down_revision = '021c397b1fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('user_images', 'images_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('images_path', sa.VARCHAR(), nullable=True))
    op.drop_column('user_images', 'image_path')
    # ### end Alembic commands ###
